---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher-server
  namespace: infrastructure
spec:
  destination:
    namespace: cattle-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: rancher
    repoURL: https://releases.rancher.com/server-charts/stable
    targetRevision: v2.7.4
    helm:
      parameters:
      - name: hostname
        value: rancher.localhost
      - name: bootstrapPassword
        value: admin
      data: |
        kubeVersion: < 1.27.0-0
  syncPolicy:
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 5
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
