---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher-server
  namespace: argocd
spec:
  destination:
    namespace: cattle-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: rancher
    repoURL: https://releases.rancher.com/server-charts/latest
    targetRevision: v2.7.5-rc4
    helm:
      parameters:
      - name: hostname
        value: rancher.ahu
      - name: bootstrapPassword
        value: admin
  syncPolicy:
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 5
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
