apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
  namespace: infrastructure
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/peshay/k8s_local
    targetRevision: HEAD
    path: ./
  destination:
    server: https://kubernetes.default.svc
    namespace: infrastructure