---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-app
  namespace: argocd
spec:
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: v23.2.0
    helm:
      values: |
        service:
          type: NodePort
          externalIPs:
            - 192.168.178.151
        ports:
          websecure:
            ## -- Enable this entrypoint as a default entrypoint. When a service doesn't explicitly set an entrypoint it will only use this entrypoint.
            # asDefault: true
            port: 8443
            # hostPort: 8443
            # containerPort: 8443
            expose: true
            exposedPort: 443          
        metrics:
          prometheus: null
        # Create an IngressRoute for the dashboard
        ingressRoute:
          dashboard:
            enabled: true
            # Custom match rule with host domain
            matchRule: Host(`traefik.ahu`)
            entryPoints: ["websecure"]
  syncPolicy:
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 5
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
