---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-app
  namespace: argocd
spec:
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: v23.1.0
  syncPolicy:
    syncOptions:
    - CreateNamespace=true