---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gocd-app
  namespace: infrastructure
spec:
  destination:
    namespace: homelab
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: gocd
    repoURL: https://gocd.github.io/helm-chart
    targetRevision: 2.1.8
