apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: infrastructure
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    namespace: infrastructure
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: apps/rancher
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}