---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-app
  namespace: infrastructure
spec:
  destination:
    namespace: infrastructure
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.57.1
    helm:
      values: |
        dashboards:
          default:
            argocd-stats:
              url: https://raw.githubusercontent.com/argoproj/argo-cd/master/examples/dashboard.json
        ingress:
          enabled: "true"
          hosts:
            - grafana.localhost
