---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-app
  namespace: monitoring
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: observability
  source:
    chart: prometheus
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 22.6.2
    helm:
      values: |
        ingress:
          ## If true, Prometheus server Ingress will be created
          ##
          enabled: true

          ## Prometheus server Ingress hostnames
          ## Must be provided if Ingress is enabled
          ##
          hosts:
            - prometheus.localhost
    syncOptions:
    - CreateNamespace=true
