apiVersion: v1
kind: Service
metadata:
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: traefik-prometheus
    app.kubernetes.io/instance: traefik-kube-system
    app.kubernetes.io/name: traefik
  name: traefik-prometheus
  namespace: kube-system
spec:
  allocateLoadBalancerNodePorts: true
  ports:
  - name: metrics
    nodePort: 31880
    port: 9100
    protocol: TCP
    targetPort: metrics
  selector:
    app: traefik-prometheus
    app.kubernetes.io/instance: traefik-kube-system
    app.kubernetes.io/name: traefik
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
